config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  	root 'welcome#index'

  	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'

	get '/about', to: 'welcome#about'
	get '/contact', to: 'welcome#contact'
	get 'help', to: "welcome#help"

	get '/login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	
	resources :users
	resources :groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :users
	has_many :posts	
end

app/models/group_membership.rb
class GroupMembership < ApplicationRecord
	belongs_to :user
	belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :group
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

	has_many :groups, :through => :group_memberships
	has_many :group_memberships
	has_many :posts
	has_many :comments


	# User input restrictions
  	validates :name,  presence: true, length: { within: 3..20 }
  	
  	before_save { self.email.downcase! }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, confirmation: true, length: { :within => 6..20 }


    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end 

    def authenticated(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
      update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	
  end

  def create
  	@user = User.find_by(email: params[:session][:email].downcase)
  	if (@user && @user.authenticate(params[:session][:password]))
  		log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
  		redirect_to @user
  	else
  		flash[:danger] = "Invalid username/password!"
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def create
		@user = User.new(user_params)
		if(@user.save)
			log_in @user
			remember user
			flash[:success] = "Succesful creation!"
			redirect_to @user
		else
			flash[:danger] = "Failed creation!"
			render 'new'
		end
	end

	def new
		@user = User.new
	end

	def show
  		@user = User.find(params[:id])
  	end
	

	private

	  def user_params
	  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def help
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def tab_title(page_title = '')
	  	if(page_title.empty?)
	  		"groupUp"
	  	else
	  		"groupUp | #{page_title}"
	  	end
	end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if (user_id = session[:user_id])
	    	@current_user ||= User.find_by(id: user_id)
	    elsif (user_id = cookies.signed[:user_id])
	     	user = User.find_by(id: user_id)
	      	if user && user.authenticated?(cookies[:remember_token])
	       		log_in user
	        	@current_user = user
	      	end
	    end
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		forget current_user
		session.delete(:user_id)
		@current_user = nil
	end

	def remember(user)
    	user.remember
    	cookies.permanent.signed[:user_id] = user.id
    	cookies.permanent[:remember_token] = user.remember_token
  	end

  	def forget(user)
  		user.forget
  		cookies.delete(:user_id)
  		cookies.delete(:remember_token)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    groupUp by Pablo Velasco
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!--
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    [if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "groupUp", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <% if logged_in? %>
              <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
                <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
              <li> <%= link_to "Log out", logout_path, method: :delete %> </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
  </body>
</html>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title><%= tab_title(yield(:title))  %></title>    
    <%= render 'layouts/rails_default' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>

<h1>Sign up!</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name  + " | User Profile") %>
<%= @user.name %>, <%= @user.email %>, Created on:<%= @user.created_at.to_s %>, Updated on: <%= @user.updated_at.to_s %></br> The time is <%= Time.now %>

app/views/welcome/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>

<body class="text-center">groupUp is a web application started by Pablo Velasco for fun.</body>

app/views/welcome/contact.html.erb
<% provide(:title, "Contact Us") %>
<h1>Contact Us</h1>
<a href="https://github.com/Pulv">Link to my github</a>

app/views/welcome/help.html.erb
<% provide(:title, "Help") %>
<h1> Placeholder </h1>

app/views/welcome/index.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to groupUp!</h1>
	<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  <h2> This is the homepage for groupUp, an application for finding and creating groups to interact with others!
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary btn-md" %>
</div>